#ifndef UARTTEST_MOVEMENTTABLE_H
#define UARTTEST_MOVEMENTTABLE_H
#include "Servo.h"
void movement_highlifting_forward();
void movement_highlifting_backward();
void movement_normal_forward();
void movement_normal_backward();
void movement_rotate_left();
void movement_rotate_right();
void movement_turn_left();
void movement_turn_right();
void movement_normal_leftward();
void movement_normal_rightward();
void movement_lowdown();
void movement_lift_up();
void movement_twist();
void movement_default_pos();
void movement_upper_rolling_pos();
void movement_rolling_backward();
void movement_convert();
void movement_wave_forward();
void movement_tetrapod_forward();
void movement_ripple_forward();
void movement_stand_up();
void movement_twist_rotate_right();
void movement_asyn_rolling();
void movement_up_hold();
void movement_up_crawl_hold();
void movement_up_half_open();
void movement_leg_hold_up();
void rolling_down();
void up_down_down();
void convert_on_and_on();
#endif //UARTTEST_MOVEMENTTABLE_H